name: 🧠 It's something else
description: Need to open an issue for something that isn't a bug, feature, or command? This template has you covered!
labels: [needs categorization,under review]
body:
  - type: dropdown
    id: category
    attributes:
      label: 🐛 Category
      description: What type of issue are you trying to report?
      options:
        - 💽 Repository
        - 🛝 GitHub Actions
        - 📃 Documentation
        - 😖 Other
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of are you currently using?
      options:
        - 🐣 Pre-Release
        - ⛔ Not Applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤔 What's happening?
      description: Please give a brief explanation and a sample implementation.
  - type: textarea
    attributes:
      label: 📝 What was your expectation?
      description: Please give a brief explanation.
